site_name: L’Internet des Lieux
site_url: https://theinternetofplaces.org/

nav:
  - index.md
  - spotin.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  language: fr

  font: false

  logo: assets/images/logo.png
  favicon: assets/images/favicon.png